[package]
name = "conrod_thread"
version = "0.1.0"
authors = ["alanpoon"]

[dependencies]
conrod = { path ="../conrod", features = ["glium","winit"]}
conrod_derive = { path ="../conrod/conrod_derive"}
greed_websocket = {path ="../greed_websocket"}
itertools = "0.4.4"
image ="*"
find_folder ="*"